version: '3'
    
services:
  database:
    image: victoryssmile/mysql-database:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=appuser123
    ports: 
      - "3308:3306"
    networks:
      - emp-network
    volumes:
      - db-data
    healthcheck:
      test: "nc -z localhost 3308"
      interval: 1s
      retries: 120
      
  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
     # Uncomment to disable scribe
      # - SCRIBE_ENABLED=false
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to enable debug logging
      # - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG
    expose:
      - 9411
    ports:
      - "9411:9411"
    networks:
      - emp-network
        
  registry-server:
    image: victoryssmile/springboot-microservice-registry-server:0.0.1-SNAPSHOT
    container_name: registry-server
    expose:
      - 8761
    ports:
      - "8761:8761"
    networks:
      - emp-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      
  config-server:
    image: victoryssmile/springboot-microservice-config-server:0.0.1-SNAPSHOT
    container_name: config-server
    expose:
      - 8888
    ports:
      - "8888:8888"
    networks:
      - "emp-network"
    depends_on:
      - registry-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry-server:8761/eureka
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    entrypoint: ["./wait-for-it.sh", "registry-server:8761", "--timeout=0","--strict", "--", "java", "-jar","app.jar" ]
    
  auth-service:
    image: victoryssmile/springboot-microservice-auth-service:0.0.1-SNAPSHOT
    container_name: auth-service
    expose:
      - 9100
    ports:
      - "9100:9100"
    networks:
      - "emp-network"
    #restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - registry-server
      - config-server
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    entrypoint: ["./wait-for-it.sh", "config-server:8888", "--timeout=0","--strict", "--", "java", "-jar","app.jar" ]
      
  contact-service:
    image: victoryssmile/springboot-microservice-contact-service:0.0.1-SNAPSHOT
    container_name: contact-service
    expose:
      - 8100
    ports:
      - "8100:8100"
    networks:
      - "emp-network"
    depends_on:
      - registry-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
#    entrypoint: ["./wait-for-it.sh", "config-server:8888", "--timeout=0","--strict", "--", "java", "-jar","app.jar" ]
    entrypoint: ["./wait-for-it.sh", "auth-service:9100", "--timeout=0","--strict", "--", "java", "-jar","app.jar" ]
    
  project-service:
    image: victoryssmile/springboot-microservice-project-service:0.0.1-SNAPSHOT
    container_name: project-service
    expose:
      - 8200
    ports:
      - "8200:8200"
    networks:
      - "emp-network"
    depends_on:
      - registry-server
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
#    entrypoint: ["./wait-for-it.sh", "config-server:8888", "--timeout=0","--strict", "--", "java", "-jar","app.jar" ]
    entrypoint: ["./wait-for-it.sh", "contact-service:8100", "--timeout=0","--strict", "--", "java", "-jar","app.jar" ]
  
  test-service:
    image: victoryssmile/springboot-microservice-test-service:0.0.1-SNAPSHOT
    container_name: test-service
    expose:
      - 8300
    ports:
      - "8300:8300"
    networks:
      - "emp-network"
    depends_on:
      - registry-server
      - config-server
#   restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/my_database?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=app_user
      - SPRING_DATASOURCE_PASSWORD=test123   
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry-server:8761/eureka 
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
#    entrypoint: ["./wait-for-it.sh", "config-server:8888", "--timeout=0","--strict", "--", "java", "-jar","app.jar" ]
    entrypoint: ["./wait-for-it.sh", "project-service:8200", "--timeout=0","--strict", "--", "java", "-jar","app.jar" ]
    
  gateway-service:
    image: victoryssmile/springboot-microservice-gateway-service:0.0.1-SNAPSHOT
    container_name: gateway-service
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - emp-network
    depends_on:
      - auth-service
#   restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
#    entrypoint: ["./wait-for-it.sh", "test-service:8300", "--timeout=0","--strict", "--", "java", "-jar","app.jar" ]
    entrypoint: ["./wait-for-it.sh", "test-service:8300", "--timeout=0","--strict", "--", "java", "-jar","app.jar" ]
      
networks:
  emp-network:
    driver: bridge  
    
volumes:
  db-data:        
